### ISSUE TITLE
Distribute examples as JSON

### ISSUE THREAD

**Issue by chrisjsewell** [executablebooks/myst-spec#27]
Then you can import them directly for testing (with https://www.typescriptlang.org/tsconfig#resolveJsonModule)

**Comment by chrisjsewell** [comment]
(i.e. `import * as data from 'myst-spec/dist/examples/commonmark.basic.json'`

**Comment by rowanc1** [comment]
The JSON should be there?

https://unpkg.com/browse/myst-spec@0.0.3/dist/

See the `myst.tests.json` does the import work? This is the full test suite, but can be stripped down by title I think?

**Comment by chrisjsewell** [comment]
Ah yeh missed that cheers.

But, as just mentioned on slack, it might be helpful to allow for breaking down by "category" i.e. the original filenames.
Either having the tests as separate JSON, or appending it to each test case dict.

For, https://github.com/executablebooks/unified-myst, I wanted to start introducing the tests incrementally (starting with the "basic" commonmark ones)

**Comment by chrisjsewell** [comment]
No worries, I figured it out
