### ISSUE TITLE
mystRole/mystDirective: use `name` instead of `kind`

### ISSUE THREAD

**Issue by chrisjsewell** [executablebooks/myst-spec#31]
In `unified-myst` I currently use `name`, e.g. for `` {name}`content` ``, rather than `kind`

This also syncs with: https://github.com/syntax-tree/mdast-util-directive/blob/4c494b18ac31f27f67b95b917aacc03207d9584f/complex-types.d.ts#L7

Any major objections to changing that here @rowanc1 @fwkoch?

**Comment by rowanc1** [comment]
This is for directive names? That sounds fine.

For admonitions, I think we still have a type=admonition, and `kind=warning`, because those are **_enums_** that are well defined?
